//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievements
    {
        public int Id { get; set; }
        public int ExProID { get; set; }
        public Nullable<int> A1 { get; set; }
        public Nullable<int> A2 { get; set; }
        public Nullable<int> A3 { get; set; }
        public Nullable<int> A4 { get; set; }
        public Nullable<int> A5 { get; set; }
        public Nullable<int> A6 { get; set; }
        public Nullable<int> A7 { get; set; }
        public Nullable<int> A8 { get; set; }
        public Nullable<int> A9 { get; set; }
        public Nullable<int> A0 { get; set; }
    
        public virtual ExPro ExPro { get; set; }
    }
}
