//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> IsOpen { get; set; }
        public Nullable<bool> IsBinary { get; set; }
        public string FEMTE { get; set; }
        public string FT { get; set; }
        public Nullable<bool> IsExtended { get; set; }
        public Nullable<bool> IsMine { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<System.DateTime> Last { get; set; }
    }
}
