//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pq
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExtensionlessBaseEntities : DbContext
    {
        public ExtensionlessBaseEntities()
            : base("name=ExtensionlessBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievements> Achievements { get; set; }
        public virtual DbSet<Ex> Ex { get; set; }
        public virtual DbSet<ExPro> ExPro { get; set; }
        public virtual DbSet<Inst> Inst { get; set; }
        public virtual DbSet<Setting> Setting { get; set; }
    }
}
