//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pq
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExPro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExPro()
        {
            this.Achievements = new HashSet<Achievements>();
            this.Setting = new HashSet<Setting>();
        }
    
        public int Id { get; set; }
        public string WinUsername { get; set; }
        public string ExUsername { get; set; }
        public string ExID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string WinDomain { get; set; }
        public string DonateUrl { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> ShareDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Achievements> Achievements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setting> Setting { get; set; }
    }
}
