//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public bool IsExtended { get; set; }
        public bool IsMine { get; set; }
        public bool DoAsk { get; set; }
        public int ExProID { get; set; }
        public bool DoAsk2 { get; set; }
    
        public virtual ExPro ExPro { get; set; }
    }
}
