//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pq
{
    using System;
    using System.Collections.Generic;
    
    public partial class x10ss
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Country { get; set; }
        public string DonationURL { get; set; }
        public Nullable<bool> Sound { get; set; }
        public Nullable<bool> Theme { get; set; }
        public Nullable<int> Color { get; set; }
        public string ExtensionlessID { get; set; }
        public string FolderPath { get; set; }
        public string FileList { get; set; }
        public string WindowsUsername { get; set; }
    }
}
