namespace pq.Model
{
    public enum FileExtensionTypeEnum
    {
        ANTE,  A, AAC, ACCDB, ACCFT, ACO, ADT, ADX, ADZ, AGDA, AGR, AHK, AI, AIFF, AIFC, AIO, AMF, AMG, AML, AMLX, AMPL, AMR, AMV, ANI, ANN, APE, APK, ARC, ART, ARW, ASAX, ASCX, ASF, ASHX, ASM, ASPX, ASX, ATG, AT3, AU, AVI, AVIF, AWK, WX, AXF, B, B64, BAK, BAR, BAS, BAT, BDF, BDT, BEAM, BIB, BIN, BLEND, BM3, BMP, BPS, BR7, BSK, BSON, BSP, BYU, BZ2, C, CPP, C32, CAB, CBL, CBT, CC, CD, CDF, CDP, CDR, CDXML, CER, CGM, CHM, CHO, CIA, CIF, CLASS, CLS, CMD, CML, CMOD, CN1, CNOF, COB, COE, COFF, COL, COMPILE, CONFIG, CPC, CPIO, CPL, CPY, CR2, CRAI, CRAFT, CRT, CS, CSPROJ, CSS, CSV, CUB, CUBE, CUR, D, DAA, DAE, DAF, DPFHTML, DPFSTICKERS, DAT, DATS, DB, DBA, DBF, DBG, DEB, DEM, DGN, DICOM, DIF, DIRED, DIVIX, DMG, DMP, DN, DNG, DO, DOC, DOCM, DOCX, DOT, DOTX, DPX, DRC, DSC, DTA, DTD, DVC, DWF, DWG, DX, DXF, E, E00, E2D, E57, EBD, EC, ECC, EDE, EDF, EFI, EIS, EL, ELC, ELF, EMAIL, EMAKER, EMF, EML, EMZ, EOT, EP, EPA, EPS, EPUB, EU4, ERL, ES6, ESCPCB, ESCSCH, ESD, ESF, ETL, EVT, EVTX, EX, EXE, EXP, EXR, EXS, F, F01, F03, F08, F18, F4, F4V, F77, F90, F95, FA, FAA, FACTOR, FASTA, FASTQ, FB, FB2, FBX, FCHK, FCS, FEN, FF, FFAPX, FFN, FIT, FITS, FLAC, FLAME, FLP, FLV, FMU, FNA, FNI, FODG, FODP, FODS, FODT, FOR, FQL, FREQ, FRAG, FRQ7, FS, FTH, G4, G6, GB, GBK, GBX, GDF, GDSCRIPT, GDT, GED, GEOJSON, GEOTIFF, GGB, GIF, GM9, GMEZ, GMI, GMK, GML, GO, GODOT, GPX, GRAPHML, GRB, GREXLI, GRIB, GRP, GSF, GTF, GV, GW, GXL, GZ, H, HA, JACK, HAR, HDF, JDF5, HDI, HDMP, HEIC, HEIF, HH, HIF, HOF, HOI4, HPP, HTA, HTM, HTML, HUM, HXX, IC, ICAL, ICC, ICE, ICL, ICNS, ICO, ICS, IFB, IFC, IGC, IGES, IMG, INI, IO, IOS, IPT, IPTRACE, IQBLOCKS, IRX, ISO, ISS, IT, JL, J2C, J2K, JAR, JAV, JAVA, JBEAM, JBIG, JCM, JDX, JNLP, JPE, JPEG, JPG, JS, JSON, JSP, JUMP, JVX, JXL, KEXTRACTION, KEY, KLC, KML, KMZ, KO, KRA, KRABER, KSH, KT, KV, LABEL, LM, LATEX, LBR, LDB, LL, LDT, LGR, LHA, LISP, LMD, LNK, LOGICX, LRC, LUA, LWO, LZ, M, M2TS, M3U, M3U8, M4A, M4P, M4R, M4V, M64, MA, MAT, MBOX, MCADDON, MCMETA, MCPACK, MCPROJECT, MCSTRUCTURE, MCTEMPLATE, MCWORLD, MCF, MD, MDB, MDF, MDI, MDG, MDL, MDMP, MDS, MEX, MGF, MHT, MID, MKA, MKV, MIX, MM, MML, MNT, MO, MOBI, MOD, MODULES, MOE, MOL, MOP, MOV, MP2, MP3, MP4, MPA, MPC, MPD, MPEG, MPG, MPS, MR, MRSH, MSC, MSCZ, MSAV, MSCH, MSDL, MSF, MSI, MSO, MSSTYLES, MSU, MTS, MUP, MX, MXF, MYD, MYI, NB, NC, NCD, NDK, NDS, NEF, NEO, NEU, NEX, NF, NFO, NIM, NMF, NOFF, NPR, NRO, NRW, NRX, NS1, NSA, NSF, NSP, NSV, NUMBERS, NWD, NWF, NXS, O, OBJ, OBS, OCX, ODB, ODF, ODG, ODP, ODS, ODT, OFF, OGA, OGV, OGX, OPUS, ORG, OSB, OSC, OSK, OSM, OSR, OST, OSU, OSZ, OTB, OTF, OTL, OTG, OTP, OTS, OTT, OV2, OWL, OXT, P, P8, P10, P12, PACK, PAGES, PAK, PAL, PAM, PAPA, PAR, PAR2, PARAMS, PAS, PAX, PBLIB, PBM, PBO, PCAP, PCL, PCS, PCX, PDB, PDE, PDF, PDI, PDM, PDN, PDS, PEM, PET, PFA, PFAM, PFB, PFC, PFM, PGN, PFX, PHF, PHN, PHP, PHP3, PHP4, PHR, PHY, PHZ, PIE, PIR, PIT, PK3, PKL, PKA, PKG, PL, PLANET, PLI, PLR, PLS, PM, PMA, PMP, PNG, POM, PPEG, PPTX, PPSX, PRJ, PROPERTIES, PROTO, PRP, PS, PSD, PSDC, PSM1, PSPPALETTE, PST, PS1, PTF, PUB, PY, QFX, QLC, QOI, QSS, QT, QTVR, R, R00, R2D, R3D, R8P, RAD, RAL, RAM, RAP, RAR, RAS, RB, RBXL, RC, RDP, RDS, RES, REX, REXX, RKT, RM, RMD, RMVB, ROB, ROL, RPM, RS, RSM, RSA, RSL, RSLS, RSLF, RUA, RUN, S, S3M, S7I, SAIF, SASS, SAT, SAV, SB, SB2, SB3, SBH, SBV, SBX, SCALA, SCM, SCR, SCSS, SDF, SD7, SDNN, SDS, SDTS, SEC, SED, SEQ, NUSERIESLL, SF, SFB, SFH, SFX, SH, SHAR, SHTM, SHTML, SHX, SIX, SIG, SL, SLDASM, SLDPRT, SM, SMCLVL, SMK, SNO, SO, SPF, SPIFF, SPIN, SPS, SPT, SPV, SPX, SPZ, SQL, SRT, SRX, SSC, ST, STC, STD, STEP, STK, STL, STI, STM, STO, STORY, STP, STW, STX, STYL, SVC, SVELETE, SVG, SWF, SWG, SWIFT, SWM, SXC, SXD, SXG, SXI, SXM, SXW, SYLK, SYMBOLICLINK, TAK, TAR, TAZ, TB2, TBZ, TBZ2, TC, TER, TGA, TGT, THM, TIF, TLB, TLZ, TMP, TORRENT, TQL, TS, TSCN, TSV, TTC, TWB, TXZ, TZ3, TZST, UI, UMP, UNV, UNX, UOS, UOT, UPD, UPS, URL, USDZ, USTX, UTI, UXF, V, V3, V4P, V46, VB, VBOX, VBPROJ, VBR, VBS, VBX, VC, VC6, VCLS, VDA, VDI, VDW, VDX, VFD, VI, VMCZ, VMDK, VMG, VOB, VMX, VPK, VPM, VPP, VPR, VQM, VRB, VS, VSD, VSDX, VSOX, VSM, VSQ, VSQX, VST, VSVNBAK, VTF, VUE, VVVVVV, WAB, WWAD, WAV, WEBM, WIN, WHEEL, WK1, WK3, WKS, WL, WLMP, WLS, VMA, WMDB, WMF, WMV, WOFF, WOFF2, WOS, WPS, WS, WSC, WTX, WUHB, X, X3D, XAR, XBRL, XCF, XDELTA, XDM, XE, XEX, XLR, XLS, XLSB, XLSM, XLSX, XM, XML, XP, XPL, XPS, XSD, XSF, XSL, XSLT, XSN, XSPF, XX, XXE, XXX, XYZ, XZ, Y, YML, YAML, YYMP, YYMPS, YYP, YYZ, ZIP, ZRX, ZS, ZST
    }

    public enum FileExtensionMidTypeEnum
    {
        Generic,
        Database,
        Shell,
        Vector,
        Raster,
        Video,
        Audio,
        Archive,
        Log,
        Style,
        Markup,
        Frontend,
        Backend,
        OOPL,
        Font,
        Executible,
        Setup,
        System,
        RichText,
        Sheets,
        Presentation,
        Script,
        Configuration,
        Library,
        Data,
        None,
        Game,
        Internet,
        Map,
        Save,
        Engine,
        ROM,
        AppData,
        Mesh,
        Console
    }
}
